FROM node:20

RUN npm install -g pnpm

RUN pmpn drizzle-kit push \
      --dialect=mysql \
      --host=$DB_HOST \
      --user=$DB_USER \
      --password=$MYSQL_PASSWORD \
      --database=$MYSQL_DATABASE

CMD ["pnpm", "tsx", "addTestData.ts"]

