services:
  lantana-datagarden-nextjs:
    build:
      dockerfile: ./Dockerfile.nextjs
    container_name: lantana-datagarden-nextjs
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - .env.development:/app/.env
      - .:/app
    tmpfs:
      - /app/.next

  database:
    build:
      dockerfile: ./Dockerfile.mysql
    container_name: database
    env_file:
      - .env.development
    # 注. テスト用、データは永続しない
    tmpfs:
      - /var/lib/mysql
    environment:
      TZ: 'Asia/Tokyo'
      LANG: 'ja_JP.UTF-8'
    cap_add:
      - SYS_NICE
    healthcheck:
      test: mysql -u $$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE -e "select 1;"
      interval: 5s
      timeout: 20s
      retries: 3
      start_period: 5s

  database-preparation:
    image: node:20
    #build:
    #  dockerfile: ./Dockerfile.database-preparation
    container_name: database-preparation
    env_file:
      - .env.development
    environment:
      NODE_ENV: 'development'
    volumes:
      - ./:/app:ro
    working_dir: /app
    command: >
      bash -c '
        npm install -g pnpm \
        && pnpm drizzle-kit push \
          --dialect=mysql \
          --schema=./src/db/schema.ts \
          --host=$$DB_HOST \
          --user=$$MYSQL_USER \
          --password=$$MYSQL_PASSWORD \
          --database=$$MYSQL_DATABASE; \
        pnpm tsx addTestData.ts
      '
    depends_on:
      database:
        condition: service_healthy
    
  webserver:
    image: nginx
    container_name: lantana-datagarden-webserver
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  default:
    name: lantana-datagarden-network

