import clsx from 'clsx';
import './global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          'bg-slate-200',
        )}
      >
        {children}
      </body>
    </html>
  )
}

